# Use root/example as user/password credentials
version: '3.4'

services:

  mongo:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    restart: always
    volumes:
      - ./.docker/mongodb/mongod.conf:/etc/mongod.conf
      - ./.docker/mongodb/initdb.d/:/docker-entrypoint-initdb.d/
      - ./.docker/mongodb/data/db/:/data/db/
      - ./.docker/mongodb/data/log/:/var/log/mongodb/
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE:  ${MONGO_INITDB_DATABASE}
    ports:
      - 27017:27017
    command: ["-f", "/etc/mongod.conf"]

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: ${CONFIG_MONGODB_ADMINUSERNAME}
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: ${CONFIG_MONGODB_ADMINPASSWORD}