# Use root/example as user/password credentials
version: '3.4'

services:

  mongo:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    restart: always
    volumes:
      - ./.docker/mongodb/files/mongod.conf:/etc/mongod.conf
      - ./.docker/mongodb/files/initdb.d/:/docker-entrypoint-initdb.d/
      - ./home/mongodb:/home/mongodb
      - ./.docker/mongodb/data/db/:/data/db/
      - ./.docker/mongodb/data/log/:/var/log/mongodb/
    env_file:
      - .env
    ports:
      - 27017:27017
    command: ["-f", "/etc/mongod.conf"]

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    links:
    - mongo:mongo
    depends_on:
    - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}